# Simple Image Converter - Release Package Creator
# Creates a clean ZIP file ready for Chrome Web Store submission

$ErrorActionPreference = "Stop"

# Get version from manifest.json
$manifest = Get-Content -Path "manifest.json" -Raw | ConvertFrom-Json
$version = $manifest.version
$packageName = "simple-image-converter-v$version.zip"

Write-Host "========================================" -ForegroundColor Cyan
Write-Host "Simple Image Converter - Release Package" -ForegroundColor Cyan
Write-Host "Version: $version" -ForegroundColor Green
Write-Host "========================================" -ForegroundColor Cyan
Write-Host ""

# Check if output file already exists
if (Test-Path $packageName) {
    Write-Host "WARNING: Package file already exists: $packageName" -ForegroundColor Yellow
    $response = Read-Host "Overwrite? (y/n)"
    if ($response -ne "y") {
        Write-Host "Release cancelled." -ForegroundColor Red
        exit
    }
    Remove-Item $packageName
}

# Check if dist folder exists
if (-not (Test-Path "dist")) {
    Write-Host "ERROR: dist folder not found. Please run 'npm run build' first." -ForegroundColor Red
    exit 1
}

# Files and directories to include from dist folder
$filesToInclude = @(
    "dist\manifest.json",
    "dist\background.js",
    "dist\offscreen.html",
    "dist\offscreen.js",
    "dist\popup.html",
    "dist\popup.css",
    "dist\popup.js",
    "dist\options.html",
    "dist\options.css",
    "dist\options.js",
    "dist\copy-helper.js",
    "LICENSE",
    "PRIVACY.md"
)

$dirsToInclude = @(
    "dist\_locales",
    "dist\icons"
)

Write-Host "Creating release package..." -ForegroundColor Yellow
Write-Host ""

# Verify all required files exist
$allFilesExist = $true
foreach ($file in $filesToInclude) {
    if ($file -like "dist\*") {
        $checkFile = $file
    } else {
        $checkFile = $file
    }
    if (Test-Path $checkFile) {
        Write-Host "[OK] $checkFile" -ForegroundColor Green
    } else {
        Write-Host "[MISSING] $checkFile" -ForegroundColor Red
        $allFilesExist = $false
    }
}

foreach ($dir in $dirsToInclude) {
    if (Test-Path $dir) {
        Write-Host "[OK] $dir/" -ForegroundColor Green
    } else {
        Write-Host "[MISSING] $dir/" -ForegroundColor Red
        $allFilesExist = $false
    }
}

if (-not $allFilesExist) {
    Write-Host ""
    Write-Host "ERROR: Some required files are missing. Cannot create package." -ForegroundColor Red
    exit 1
}

Write-Host ""
Write-Host "Creating ZIP archive..." -ForegroundColor Yellow

# Create temporary directory for packaging
$tempDir = "temp-release-$version"
if (Test-Path $tempDir) {
    Remove-Item -Recurse -Force $tempDir
}
New-Item -ItemType Directory -Path $tempDir | Out-Null

# Copy files
foreach ($file in $filesToInclude) {
    if ($file -like "dist\*") {
        # Remove "dist\" prefix for destination
        $destFile = $file -replace "^dist\\", ""
        Copy-Item $file -Destination (Join-Path $tempDir $destFile)
    } else {
        # Files outside dist (LICENSE, PRIVACY.md)
        Copy-Item $file -Destination $tempDir
    }
}

# Copy directories
foreach ($dir in $dirsToInclude) {
    if ($dir -like "dist\*") {
        # Remove "dist\" prefix for destination
        $destDir = $dir -replace "^dist\\", ""
        Copy-Item -Recurse $dir -Destination (Join-Path $tempDir $destDir)
    } else {
        Copy-Item -Recurse $dir -Destination $tempDir
    }
}

# Find and include all chunk files (client-*.js) generated by Vite
Write-Host "Scanning for chunk files..." -ForegroundColor Yellow
$chunkFiles = Get-ChildItem -Path "dist" -Filter "client-*.js" -File
foreach ($chunkFile in $chunkFiles) {
    $destFile = Join-Path $tempDir $chunkFile.Name
    Copy-Item $chunkFile.FullName -Destination $destFile
    Write-Host "[INCLUDED] $($chunkFile.Name)" -ForegroundColor Green
}

# Create ZIP
Compress-Archive -Path "$tempDir\*" -DestinationPath $packageName -CompressionLevel Optimal

# Cleanup
Remove-Item -Recurse -Force $tempDir

Write-Host ""
Write-Host "========================================" -ForegroundColor Cyan
Write-Host "Package created successfully!" -ForegroundColor Green
Write-Host "========================================" -ForegroundColor Cyan
Write-Host ""
Write-Host "File: $packageName" -ForegroundColor White
$fileSize = (Get-Item $packageName).Length / 1KB
Write-Host "Size: $([math]::Round($fileSize, 2)) KB" -ForegroundColor White
Write-Host ""
Write-Host "Next steps:" -ForegroundColor Yellow
Write-Host "  1. Test the extension one final time" -ForegroundColor White
Write-Host "  2. Go to Chrome Web Store Developer Dashboard" -ForegroundColor White
Write-Host "  3. Upload $packageName" -ForegroundColor White
Write-Host ""
